version: 0.2
phases:
  install: #Instalar pynamodb
    runtime-versions:
      python: 3.9

  build:
    commands:
      - sam build
      - export BUCKET=aws-sam-cli-managed-default-samclisourcebucket-n1lmldaa3a6q
      - sam package --s3-bucket $BUCKET --output-template-file template.yaml

artifacts:
  type: zip
  files:
    - template.yaml